### ISSUE TITLE
Možnost darů skrze aplikaci

### ISSUE THREAD

**Issue by Deli-Sedlackova** [Loono-cz/loono-tasks#32]
# Motivace

Uživatelé by měli mít možnost skrze Preventivku darovat peníze na její další rozvoj. Jedná se o jeden ze způsobů, jak získat peníze na provoz. Časem vyhodnotíme, jak moc je tento způsob úspěšný a podle toho budeme funkcionalitu dále rozvíjet.

Uživatel nedostane za případný dar žádné výhody (body, badges, features, prémiový obsah). Pokud bude chtít dárce Loono nějak odměnit, bude to mimo aplikaci.

# Možná řešení

Zatím bychom rádi využili integraci s Darujme.cz, kde už Loono má vytvořený projekt, a proto by správa darů byla jednodušší. Představa je taková, že by se občas (intervaly musíme prodiskutovat) uživateli v aplikaci objevila výzva pro darování  - in-app notifikace, která by uživateli umožnila pomocí Darujme.cz darovat libovolnou částku. Kromě toho by někde v aplikaci (asi profil) byla možnost darovat dar kdykoli. Push notifikace na toto využívat nechceme, ty mají být informační kanálem primárně pro informace o preventivních prohlídkách.

Chceme nastavit notifikace i textaci citlivě tak, aby to uživatele neodradilo, na druhou stranu bychom rádi vytvořili komunitu, která přispívá pravidelně, i když jen malou částkou.

Vzhledem k tomu, že by darování probíhalo mimo aplikaci, nebudeme mít informace o dárcích. Z pohledu aplikace tyto informace nutně nepotřebujeme (nebudeme spojovat body/badge/prémiový obsah s tím, zda je někdo dárce nebo ne). Nicméně pokud by existovala možnost, jak o uživateli alespoň základní údaje zjistit, dalo by se to využít na personalizaci výzev pro darování (např. pokud někdo daruje pravidelně, nemusí se mu v aplikaci in-app notifikace zobrazovat ...) nebo například na nějakou pěknou děkovací hlášku.

# TODO:
- [x] potvrdit si, že podmínky apple/google store takovou integraci za účelem získání darů umožňují a jaká jsou omezení ([https://developer.apple.com/app-store/review/guidelines/#business](https://developer.apple.com/app-store/review/guidelines/#business) , [https://developer.apple.com/apple-pay/nonprofits/](https://developer.apple.com/apple-pay/nonprofits/)) @Deli-Sedlackova  

- [x] notifikace zobrazovat všem, frekvence notifikací 1x14 dní

- [x] poladit s Káťou textaci @Deli-Sedlackova 
- [x] Doplnit výzvu na Darujme, na kterou bude appka odkazovat @Deli-Sedlackova 
- [x] zjistit možnosti integrace - https://www.darujme.cz/informace-pro-neziskove-organizace/ 
  - [x] zprostředkování platby - custom pole formuláře, např. omezení možnosti platebních metod 
  - [x] informace o dárcích #33 

# Issues:
 - #61
 - https://github.com/Loono-cz/loono-be/issues/27
 - https://github.com/Loono-cz/loono/issues/342
 - https://github.com/Loono-cz/loono-tasks/issues/83

**Comment by Deli-Sedlackova** [comment]
Z callu s Darujme: 
- Je možné z widgetu získávat  data o uživatelích? V administraci darů vidíme seznam darů, kde jsou vidět statistické údaje o počtech lidí, kdo do výzvy vstoupil přes widget, apod. Konkrétní údaje o uživatelích ale dostupné nebudou. (nesbírají je)
- Jaké procento z platby si bere Apple Pay a Google Pay? Procento co se bere z plateb je stejné u všech způsobů platby (2 % z každého daru) - tzn. Darujme si žádná další procenta navíc nebere, oni mají smlouvu s Global Payments platební bránou a ti jim tam nabízejí možnosti platby. 
- Nabídka platebních metod se odvíjí od prohlížeče a ne od systému (pokud člověk kouká na iPhone, tak se mu nabídne Apple Pay)
- Zkušenosti od jiných organizací ohledně plateb v aplikacích nemají
- Testovací prostředí sandbox pro vývojáře nemají. Nedávají přístupy nikomu zvenku (není možnost si otestovat platbu bokem bez toho, aniž by člověk platil).
- Jde vynutit platební metoda do widgetů? To se dá snadno nastavit v projektu, které platební metody ne/chceme zobrazovat a na formuláři už by se měly zobrazovat jen platební metody, které si nastavíme.
