### ISSUE TITLE
Přidání samovyšetření kůže

### ISSUE THREAD

**Issue by Deli-Sedlackova** [Loono-cz/loono-tasks#50]
# Motivace

Uživatel by v sekci Prevence měl jednou měsíčně být schopen provést samovyšetření kůže. 

# Možná řešení

Karta by měla mít stejné chování jako samovyšetření prsou/varlat. Samovyšetření kůže je totožné pro muže i ženy, proto není potřeba rozlišovat texty a grafiku.

- karta Samovyšetření kůže se zobrazuje uživateli mezi ostatními prohlídkami a mění v seznamu prohlídek pozici na základě stavu vyšetření, po provedení vyšetření karta se zařadí dospodu seznamu prohlídek, po uplynutí měsíce se opět zařadí navrch a svítí uživateli jako nesplněná prohlídka, viz [Dokumentace - main screen](https://github.com/Loono-cz/loono-tasks/wiki/LOON-492-Adding-a-new-self-examination-card-to-the-main-screen)

- při rozkliknutí detailu prohlídky uživatel uvidí FAQ, a buttony "Vyšetřil jsem se" a "Jak se vyšetřit", viz [Dokumentace - detail](https://github.com/Loono-cz/loono-tasks/wiki/LOON--493-Creating-a-self-examination-detail-screen). V případě možnosti "vyšetřil jsem se" se zobrazí uživateli "Jak to dopadlo?" s možnostmi "Něco jsem si našel" a "Je to v pořádku", viz [Dokumentace - Bottom sheet "jak to dopadlo" ](https://github.com/Loono-cz/loono-tasks/wiki/LOON-494-Creating-bottom-sheet-%22jak-to-dopadlo%22)
- v případě možnosti "Jak se vyšetřit" se uživateli zobrazí návod na vyšetření, viz. [Dokumentace -  Screen with educational video](https://github.com/Loono-cz/loono-tasks/wiki/LOON-495-Creating-new-screen-with-educational-video)
- notifikace popsane zde: [LOON-394 Push notification](https://github.com/Loono-cz/loono-tasks/wiki/LOON-394-Samovy%C5%A1et%C5%99en%C3%AD-prsu-varlat-Push-notification)

# TODO

-  [x] potvrdit chování po případném nálezu (aktuálně se po nahlášení nálezu posílá notifikace po 56 dnech, viz. [LOON-499 Creating "jak-dopadlo-vyšetření"](https://github.com/Loono-cz/loono-tasks/wiki/LOON-499-Creating-%22jak-dopadlo-vyšetřen%C3%AD%22) @Deli-Sedlackova - Ano, chování i intervaly by měly být stejné jako u prsou/varlat
- [x] potvrdit notifikace - jak často a kdy posílat/neposílat @Deli-Sedlackova: Frekvence stejná jako u samovyšetření prsou/varlat
- [x] doplnit texty @Deli-Sedlackova: texty dostupné ZDE: [https://docs.google.com/document/d/1hAWfLulvGlM3hMYRz8ScURpL1nAc09Iz6gyTONGsIrs/edit?usp=sharing](url)
- [x] doplnit obrázky @Deli-Sedlackova - bude doplněno 19.7.
- [ ] doplnit video samovyšetření @Deli-Sedlackova bude doplněno 22.8.

![Image](https://user-images.githubusercontent.com/98404015/179920811-31d8755e-99ab-413b-a081-2612b8d72d9f.svg)
![Image](https://user-images.githubusercontent.com/98404015/179920810-3a10bdbb-0706-452f-b18d-6d1f94cc0f1d.svg)

# Issues
- #60
- https://github.com/Loono-cz/loono-be/issues/28
- https://github.com/Loono-cz/loono/issues/343

**Comment by Deli-Sedlackova** [comment]
Prozatimní video je ZDE: [https://drive.google.com/file/d/1gJBoOZAf4_WO_gIqUFk2VTKyWaK8HVzh/view?usp=sharing](url) Video bude do konce roku 2022 aktualizováno.
